name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 只有推送 tag 时才触发

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pyinstaller PyQt5

      - name: Clean old build files
        run: |
          if (Test-Path dist_build) { Remove-Item -Recurse -Force dist_build }
          if (Test-Path 一二布布.spec) { Remove-Item -Force 一二布布.spec }

      - name: Build exe
        run: |
          pyinstaller --clean --noconsole --onefile --name "一二布布" --distpath dist_build --workpath dist_build/build --specpath dist_build --exclude-module test --exclude-module tkinter --add-data "icon/output.png;icon" transparent_gif_player.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist_build/一二布布.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}